name: "Continuous Deploy"
on:
    workflow_run:
        workflows: ["Integration"]
        types:
            - completed
jobs:
    pull_and_run_code:
        runs-on: self-hosted
        steps:
            - name: # Update Computer
              run: |
                sudo apt-get update
                sudo apt-get upgrade -y
            - name: # Install Helm Package manager
              run: |
                curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
                sudo apt-get install apt-transport-https --yes
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
                sudo apt-get update
                sudo apt-get install helm -y

            - name: # Installing the chart
              run: |
                helm create simple-P
                helm template simple-P simple-P
                helm install simple-P simple-P
            
            - name: # Installing Prometheus
              run: |
                helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
                helm repo add stable https://charts.helm.sh/stable
                helm repo update
                helm install prometheus prometheus-community/prometheus
            
            ## Installation of Docker engine
            - name: "Docker install"
              run: |
                # Add Docker's official GPG key:
                sudo apt-get update
                sudo apt-get install ca-certificates curl
                sudo install -m 0755 -d /etc/apt/keyrings
                sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
                sudo chmod a+r /etc/apt/keyrings/docker.asc
      
            # Add the repository to Apt sources:
            - name: "Repository key"
              run: |
                echo \
                    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
                    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
                    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                sudo apt-get update
            ## Install Docker Engine
            - name: Installing Docker engine
              run: |
                sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
        
            ## Pulling and running the container
            - name: "Remove container spcool"
              run: "sudo docker rm -f spcool || true"
            
            - name: "Get the code from Docker Hub"
              run: "sudo docker pull seun007/spcool:1"
            
            - name: "Run the image as a container"
              run: sudo docker run -d -p 80:80 --name spcool seun007/spcool:1
