name: "Continuous Deploy"
on:
    workflow_run:
        workflows: ["Integration"]
        types:
            - completed
jobs:
    pull_and_run_code:
        runs-on: self-hosted
        steps:
            - name: "Remove conatiner SPP"
              run: "sudo docker rm -f SPP || true"
            
            - name: "Get the code from Docker Hub"
              run: "sudo docker pull seun007/SPP:1"
            
            - name: "Run the image as a container"
              run: "sudo docker run -d -p 80:80 --name SPP seun007/SPP:1"  
