name: Deployment Workflow
on:
  push:
    branches:
      - master

jobs:
  preparation:
    runs-on: ubuntu-la
    steps:
      - name: preparation
        run: echo "preparing the table ...."
        
      - name: checks out the repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Install EKSCTL
      - name: installing eksctl
        run: |
            # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7`
            ARCH=amd64
            PLATFORM=$(uname -s)_$ARCH
        
            curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
        
            # (Optional) Verify checksum
            curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
        
            tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
        
            sudo mv /tmp/eksctl /usr/local/bin

      - name: creating cluster
        run: |
          eksctl create cluster --name simple \
          --nodegroup-name simple \
          --node-type t2.large \
          --nodes 4 \
          --nodes-max 4 \
          --nodes-min 2 \
          --managed

      - name: creating self hosted runner
        run: |
          mkdir actions-runner && cd actions-runner
          curl -o actions-runner-linux-x64-2.313.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.313.0/actions-runner-linux-x64-2.313.0.tar.gz
          echo "56910d6628b41f99d9a1c5fe9df54981ad5d8c9e42fc14899dcc177e222e71c4  actions-runner-linux-x64-2.313.0.tar.gz" | shasum -a 256 -c
          tar xzf ./actions-runner-linux-x64-2.313.0.tar.gz
          ./config.sh --url https://github.com/seunhub007/SimplePersonal2 --token A4ZVN35YFZJWESFGNTSY4UDFZPNKW
          ./run.sh
          
        

      - name: setup OIDC
        run: |
          cluster_name=simple
          oidc_id=$(aws eks describe-cluster --name $cluster_name --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5)
          aws iam list-open-id-connect-providers | grep $oidc_id | cut -d "/" -f4
          eksctl utils associate-iam-oidc-provider --cluster $cluster_name --approve

      - name: create a service account
        run: |
          echo "Creating service account..."
          cluster_name=simple
          eksctl create iamserviceaccount \
          --name ebs-csi-controller-sa \
          --namespace kube-system \
          --cluster $cluster_name \
          --role-name AmazonEKS_EBS_CSI_DriverRole \
          --role-only \
          --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
          --approve

      - name: add the EBS-CSI addon
        run: |
          cluster_name=simple
          echo "Adding EBS-CSI addon..."
          eksctl create addon --name aws-ebs-csi-driver --cluster $cluster_name --service-account-role-arn arn:aws:iam::675732258064:role/AmazonEKS_EBS_CSI_DriverRole --force
        

        
      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      - name: "Build our code"
        env:
          IMAGE_NAME: spcool
          VERSION: 1
          USERNAME: seun007
        run: |
            docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
            docker push $USERNAME/$IMAGE_NAME:$VERSION


        

            